title: Lib5K Documentation
lang: en
description: The software libraries that power all Raider Robotics projects 
baseurl: "/lib5k"

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions